services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Anyaforger_290034
      MYSQL_DATABASE: student_system
      MYSQL_USER: root
      MYSQL_PASSWORD: Anyaforger_290034
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
